FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["src/ApiGateway/ProductMesh.Gateway/ProductMesh.Gateway.csproj", "src/ApiGateway/ProductMesh.Gateway/"]
RUN dotnet restore "src/ApiGateway/ProductMesh.Gateway/ProductMesh.Gateway.csproj"
COPY . .
WORKDIR "/src/src/ApiGateway/ProductMesh.Gateway"
RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ProductMesh.Gateway.dll"]
